#!/usr/bin/env python3
"""
Package the RL bot into a submission zip for the eval server.

The zip contains one top-level folder named after the bot. When unzipped into
stellatro-tournament/submissions/, it creates the right layout for bot_server.py
to pick up.

Usage (from anywhere in the repo):
    python starter-kit/bots/rl/make_submission.py
    python starter-kit/bots/rl/make_submission.py --name my_rl_bot
    python starter-kit/bots/rl/make_submission.py --checkpoint checkpoints_v3/model_final.pt
    python starter-kit/bots/rl/make_submission.py --out /path/to/submission.zip

Zip layout:
    {name}/
    ├── bot.py          (thin wrapper — generated by this script)
    ├── rl_bot.py       (participant's copy — may contain local changes)
    ├── model.py        (participant's copy — may have custom architecture)
    ├── bots/
    │   ├── __init__.py
    │   └── utils.py
    └── model_final.pt  (bundled checkpoint)

rl_bot.py and model.py are bundled from the local repo rather than relied on
from the eval image so that custom architectures and local edits are preserved.
The generated bot.py primes sys.path with the submission directory so that
`from rl_bot import RLBot` and `from model import build_model` resolve to the
participant's files, not any stale copies in the image.
"""

import argparse
import zipfile
from pathlib import Path


RL_DIR = Path(__file__).resolve().parent
BOTS_DIR = RL_DIR.parent  # starter-kit/bots/
DEFAULT_CHECKPOINT_PATH = RL_DIR / "checkpoints" / "model_final.pt"


# Small bot.py dropped into the submission folder.
# It primes sys.path with the submission directory so all local source files
# (rl_bot.py, model.py, bots/) take precedence over anything in the image.
_BOT_PY = """\
from __future__ import annotations

import sys
from pathlib import Path

_SUBMISSION_DIR = Path(__file__).resolve().parent

# Put the submission directory first so the participant's rl_bot.py / model.py
# are used instead of any copies that may exist elsewhere in the image.
if str(_SUBMISSION_DIR) not in sys.path:
    sys.path.insert(0, str(_SUBMISSION_DIR))

from rl_bot import RLBot  # noqa: E402


class Bot(RLBot):
    def __init__(self):
        super().__init__(
            checkpoint_path=str(_SUBMISSION_DIR / "model_final.pt"),
            device="cpu",
        )
"""


def _default_checkpoint_path() -> Path | None:
    if DEFAULT_CHECKPOINT_PATH.exists():
        return DEFAULT_CHECKPOINT_PATH
    return None


def make_zip(name: str, checkpoint: Path, output: Path) -> None:
    if not checkpoint.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint}")

    source_files: list[tuple[Path, str]] = [
        (RL_DIR / "rl_bot.py",       f"{name}/rl_bot.py"),
        (RL_DIR / "model.py",         f"{name}/model.py"),
        (BOTS_DIR / "__init__.py",    f"{name}/bots/__init__.py"),
        (BOTS_DIR / "utils.py",       f"{name}/bots/utils.py"),
    ]

    missing = [src for src, _ in source_files if not src.exists()]
    if missing:
        raise FileNotFoundError(
            "Required source files not found:\n" + "\n".join(f"  {p}" for p in missing)
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{name}/bot.py", _BOT_PY)
        print(f"  {name}/bot.py{'':<44}(generated)")

        for src, arcname in source_files:
            zf.write(src, arcname)
            size_kb = src.stat().st_size / 1024
            print(f"  {arcname:<56}({size_kb:.1f} KB)")

        zf.write(checkpoint, f"{name}/model_final.pt")
        size_kb = checkpoint.stat().st_size / 1024
        print(f"  {name}/model_final.pt{'':<38}({size_kb:.1f} KB)")

    total_kb = output.stat().st_size / 1024
    print(f"\nCreated: {output}  ({total_kb:.1f} KB)")
    print(
        f"\nTo install into the tournament runner:\n"
        f"  unzip -o {output} -d stellatro-tournament/submissions/"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Package the RL bot for eval-server submission.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--name",
        default="rl",
        help="Bot name used as the submission folder name (default: rl)",
    )
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=None,
        help="Checkpoint .pt file to bundle (default: checkpoints/model_final.pt)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output zip path (default: submission_{name}.zip next to this script)",
    )
    args = parser.parse_args()

    checkpoint = args.checkpoint or _default_checkpoint_path()
    if checkpoint is None:
        raise FileNotFoundError("Checkpoint not found. Pass --checkpoint explicitly.")
    output = args.out or RL_DIR / f"submission_{args.name}.zip"
    make_zip(name=args.name, checkpoint=checkpoint, output=output)


if __name__ == "__main__":
    main()
